# Generated by Django 5.2.3 on 2025-06-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='short_summary',
            new_name='shortSummary',
        ),
    ]
