# Generated by Django 5.2.3 on 2025-06-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_short_summary_blog_shortsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='shortSummary',
            new_name='description',
        ),
    ]
